example_dag_1:
  params:
    default_args:
      start_date: 2021-04-19
      end_date: null
      retries: 1
      retry_delay_sec: 300
    schedule_interval: '0 12 * * *'
    description: 'Simple tutorial DAG'
  tasks:
    task_1:
      operator: airflow.operators.bash_operator.BashOperator
      bash_command: 'echo 1'
    task_2:
      operator: airflow.operators.bash_operator.BashOperator
      bash_command: 'echo 2'
      dependencies: [task_1]

python_dag:
  params:
    default_args:
      start_date: 2021-04-19
      end_date: null
      retries: 1
      retry_delay_sec: 300
    schedule_interval: '0 12 * * *'
    description: 'Simple tutorial DAG'
  tasks:
    task_1:
      operator: airflow.operators.python_operator.PythonOperator
      python_callable: python_operator
      python_callable_file: operators.py
